---
name: docker-alpine-build
on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'
env:
  IMAGE_NAME: whisparr
jobs:
  docker-alpine-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3
        with:
          platforms: arm,arm64

      - uses: docker/setup-buildx-action@v3

      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          tags: |
            latest
            alpine

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push multi-arch alpine image
        uses: docker/build-push-action@v4
        with:
          push: true
          provenance: false
          file: Dockerfile
          build-args: |-
            VERSION=2.0.0.548
            CHANNEL=nightly
            TARGETPLATFORM=linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          platforms: linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7
          cache-from: type=gha
          cache-to: type=gha,mode=max
